version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.10.0
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.10.0
    ports:
      - "5601:5601"

  logstash:
    image: logstash:7.10.0
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    ports:
      - "5044:5044"