- name: Configure application server
  hosts: all
  tasks:
    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Start application
      shell: |
        cd /app && python3 app.py